version: "3.5"
services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/postgres
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - SALT=${SALT}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - LANGFUSE_CSP_ENFORCE_HTTPS=${LANGFUSE_CSP_ENFORCE_HTTPS:-true}
      - AUTH_DOMAINS_WITH_SSO_ENFORCEMENT=${AUTH_DOMAINS_WITH_SSO_ENFORCEMENT}
      - AUTH_DISABLE_USERNAME_PASSWORD=${AUTH_DISABLE_USERNAME_PASSWORD:-false}
      - AUTH_DISABLE_SIGNUP=${AUTH_DISABLE_SIGNUP:-false}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - SMTP_CONNECTION_URL=${SMTP_CONNECTION_URL}
      - ENABLE_EVENT_LOG=${ENABLE_EVENT_LOG:-true}
    volumes:
      - langfuse-data:/app/data
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  langfuse-data:
  database-data:
